version: '3.8'

services:
  db:
    image: postgres:15.1
    ports:
      - ${POSTGRES_BIND}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    ports:
      - ${KEYCLOAK_ADMIN_BIND}:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    env_file: .env
    volumes:
      #  - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/data/h2:/opt/keycloak/data/h2
    # command: start-dev --import-realm
    command: start-dev

volumes:
  db_data:
  keycloak_data:
